variables:
  - group: 'jellyfin'

trigger:
  batch: true
  tags:
    include:
      - '*'

jobs:

  - job: Publish
    displayName: 'Publish'

    condition: startsWith(variables['Build.SourceBranch'], 'refs/tags')

    pool:
      vmImage: 'ubuntu-latest'

    variables:
      - name: JELLYFIN_VERSION
        value: $[replace(variables['Build.SourceBranch'],'refs/tags/v','')]

    steps:
      - task: Gradle@2
        displayName: 'Build, Distribute & Publish'
        inputs:
          gradleWrapperFile: 'gradlew'
          tasks: 'publish distZip'
          publishJUnitResults: false
          testResultsFiles: '**/TEST-*.xml'
          javaHomeOption: 'JDKVersion'
          jdkVersionOption: 1.11
          sonarQubeRunAnalysis: false
        env:
          BINTRAY_KEY: $(bintray_key)

      - task: CopyFiles@2
        displayName: 'Copy build assets'
        inputs:
          Contents: |
            **/distributions/*-$(JELLYFIN_VERSION).zip
            **/libs/*-$(JELLYFIN_VERSION).jar
            **/libs/*-$(JELLYFIN_VERSION)-sources.jar
            **/outputs/aar/*.aar
          TargetFolder: '$(Build.ArtifactStagingDirectory)'
          flattenFolders: true

      - task: GitHubRelease@1
        displayName: 'GitHub Upload'
        inputs:
          gitHubConnection: Jellyfin Release Download
          repositoryName: jellyfin/jellyfin-apiclient-java
          action: 'edit'
          assetUploadMode: 'replace'
          tag: 'v$(JELLYFIN_VERSION)'
